"""A self-contained demo library, so the whole pipeline runs with no real songs, no
downloads and no ML models.

Each "song" is synthetic: every word is a short tone burst (its pitch comes from the word)
over a quiet drone, and the transcript is written directly instead of transcribed. The
lines are invented, not real lyrics.
"""

from __future__ import annotations

import zlib
from pathlib import Path

import numpy as np

from songspeak import audio
from songspeak.library import Library, Song, Word
from songspeak.text import normalize_words

DEMO_LICENSE = "Synthetic demo audio generated by SongSpeak - no third-party rights"

DEMO_SONGS = [
    ("paper-lanterns", "Paper Lanterns", "Demo Band A", ["calm"], "hello paper lanterns hello city rain"),
    ("night-market", "Night Market", "Demo Band B", ["upbeat"], "everybody gather round the night market glow"),
    ("harbour-lights", "Harbour Lights", "Demo Band C", ["calm"], "welcome to the harbour welcome home tonight"),
    ("merlion-skies", "Merlion Skies", "Demo Band D", ["upbeat"], "we are flying back to singapore singapore sunrise"),
    ("late-train", "Late Train", "Demo Band E", ["upbeat"], "hello everybody on the late train home"),
]

DEMO_MESSAGE = "Hello, everybody. Welcome to Singapore!"

WORD_SECONDS = 0.32
WORD_GAP = 0.14


def _word_burst(word: str) -> np.ndarray:
    semitone = zlib.crc32(word.encode()) % 12
    freq = 220.0 * 2 ** (semitone / 12)
    t = np.arange(int(WORD_SECONDS * audio.SR), dtype=np.float32) / audio.SR
    wave_ = sum(np.sin(2 * np.pi * freq * k * t) / k for k in (1, 2, 3))
    envelope = np.minimum(1.0, np.minimum(t / 0.03, (WORD_SECONDS - t) / 0.08))
    return (0.3 * wave_ * envelope).astype(np.float32)


def build_demo_library(root: Path | str) -> Library:
    root = Path(root)
    (root / "audio").mkdir(parents=True, exist_ok=True)
    library = Library(root, [])

    for song_id, title, artist, moods, line in DEMO_SONGS:
        lead_in = 1.0
        pieces, words, t = [audio.silence(lead_in)], [], lead_in
        for word in normalize_words(line):
            pieces += [_word_burst(word), audio.silence(WORD_GAP)]
            words.append(Word(word, round(t, 3), round(t + WORD_SECONDS, 3), 0.95))
            t += WORD_SECONDS + WORD_GAP
        pieces.append(audio.silence(1.0))
        vocals = np.concatenate(pieces)
        drone = 0.03 * np.sin(2 * np.pi * 110 * np.arange(len(vocals)) / audio.SR).astype(np.float32)

        rel = f"audio/{song_id}.wav"
        with audio.WavWriter(root / rel) as out:
            out.write(vocals + drone)
        song = Song(id=song_id, title=title, artist=artist, audio=rel, license=DEMO_LICENSE, moods=moods)
        library.songs[song_id] = song
        library.save_transcript(song, words)

    library.save()
    return library
